'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from "react-redux"
import { store, persistor } from "./_redux/store"
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { PersistGate } from 'redux-persist/integration/react'


// export const metadata: Metadata = {
//   title: 'Create kanban app',
//   description: 'Generated by create next app asjdfkjaskdfj aklsjdflkj',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='bg-[#20212c]'>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ThemeProvider attribute='class'>
              {children}
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  )
}
