'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from "react-redux"
import { store } from "./_redux/store"
import './globals.css'
import { ThemeProvider } from 'next-themes'


// export const metadata: Metadata = {
//   title: 'Create kanban app',
//   description: 'Generated by create next app asjdfkjaskdfj aklsjdflkj',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
    <html lang="en" suppressHydrationWarning>
      <body>
      <ThemeProvider attribute='class'>
        {children}

      </ThemeProvider>
      </body>
    </html>
    </Provider>
  )
}
